apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-service
  template:
    metadata:
      labels:
        app: git-service
    spec:
      containers:
        - name: git-service
          image: rpstar/git-service:#{tag}#
          env:
            - name: NODE_ENV
              value: stg
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: git-service
spec:
  clusterIP: None
  selector:
    app: git-service
  ports:
    - port: 3000
      targetPort: 3000
