apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
        - name: orchestrator-service
          image: rpstar/orchestrator-service:latest
          env:
            - name: NODE_ENV
              value: dev
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  clusterIP: None
  selector:
    app: orchestrator-service
  ports:
    - port: 3000
      targetPort: 3000
