apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rpstar/auth-service:#{tag}#
          env:
            - name: NODE_ENV
              value: prod
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: rpstar-secrets
                  key: JWT_KEY
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  clusterIP: None
  selector:
    app: auth-service
  ports:
    - port: 3000
      targetPort: 3000
