apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-configmap
data:
  Caddyfile: |
    https://rpstar-prod.uksouth.cloudapp.azure.com
    root /srv
    gzip {
      not /api /socket.io
    }
    header / {
      #Strict-Transport-Security "max-age=31536000;"
      X-XSS-Protection "1; mode=block"
      X-Content-Type-Options "nosniff"
      X-Frame-Options "DENY"
    }
    mime .js text/javascript
    proxy /api gateway:3000 {
      transparent
    }
    proxy /socket.io gateway:3000 {
      websocket
    }
    rewrite {
      if {path} not_match ^/api
      if {path} not_match ^/socket.io
      to {path} {path}/ /
    }
    tls alin@qoffice.ro
    log stdout
    errors stdout
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-claim
spec:
  storageClassName: manual
  volumeName: caddy-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: rpstar/ui:#{tag}#
          env:
            - name: ACME_AGREE
              value: 'true'
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: caddy-persistent-storage
              mountPath: /root/.caddy
            - name: config-volume
              mountPath: /etc/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: caddy-persistent-storage
          persistentVolumeClaim:
            claimName: caddy-claim
        - name: config-volume
          configMap:
            name: ui-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
